export const ACTIONS = {
  ADD_MOVIE: "ADD MOVIE",
  APPLY_FILTER: "APPLY FILTER",
  ADD_WATCHLIST: "ADD WATCHLIST",
  REMOVE_WATCHLIST: "REMOVE WATCHLIST",
  ADD_STARRED: "ADD STARRED",
  REMOVE_STARRED: "REMOVE STARRED",
};
